// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SkuServiceClient is the client API for SkuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkuServiceClient interface {
	DecreaseStock(ctx context.Context, in *Sku, opts ...grpc.CallOption) (*Sku, error)
}

type skuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkuServiceClient(cc grpc.ClientConnInterface) SkuServiceClient {
	return &skuServiceClient{cc}
}

func (c *skuServiceClient) DecreaseStock(ctx context.Context, in *Sku, opts ...grpc.CallOption) (*Sku, error) {
	out := new(Sku)
	err := c.cc.Invoke(ctx, "/SkuService/DecreaseStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkuServiceServer is the server API for SkuService service.
// All implementations must embed UnimplementedSkuServiceServer
// for forward compatibility
type SkuServiceServer interface {
	DecreaseStock(context.Context, *Sku) (*Sku, error)
	mustEmbedUnimplementedSkuServiceServer()
}

// UnimplementedSkuServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSkuServiceServer struct {
}

func (UnimplementedSkuServiceServer) DecreaseStock(context.Context, *Sku) (*Sku, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecreaseStock not implemented")
}
func (UnimplementedSkuServiceServer) mustEmbedUnimplementedSkuServiceServer() {}

// UnsafeSkuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkuServiceServer will
// result in compilation errors.
type UnsafeSkuServiceServer interface {
	mustEmbedUnimplementedSkuServiceServer()
}

func RegisterSkuServiceServer(s grpc.ServiceRegistrar, srv SkuServiceServer) {
	s.RegisterService(&SkuService_ServiceDesc, srv)
}

func _SkuService_DecreaseStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Sku)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuServiceServer).DecreaseStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SkuService/DecreaseStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuServiceServer).DecreaseStock(ctx, req.(*Sku))
	}
	return interceptor(ctx, in, info, handler)
}

// SkuService_ServiceDesc is the grpc.ServiceDesc for SkuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SkuService",
	HandlerType: (*SkuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DecreaseStock",
			Handler:    _SkuService_DecreaseStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/sku.proto",
}
