global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'ordersvc'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['goapm-ubuntu:30001'] # use host ip
  - job_name: 'usrsvc'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['goapm-ubuntu:30012'] # use host ip
  - job_name: 'skusvc'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['goapm-ubuntu:30013'] # use host ip
